language: node_js

node_js:
  - "stable"

cache: npm

script:
  - npm run build

deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
