language: node_js

node_js:
  - "stable"
  - 10

cache: npm

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  target_branch: gh-pages
  on:
    branch: master
